//go:build !windows

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	envShName   = "env.sh"
	markerBegin = "# >>> hi-agent env >>>"
	markerEnd   = "# <<< hi-agent env <<<"
)

// setUserEnv 写入 ~/.hi-agent/env.sh，并确保 ~/.profile 与 ~/.bashrc 自动 source。
func setUserEnv(kv map[string]string) (keys []string, hint string, err error) {
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return nil, "", fmt.Errorf("无法解析 HOME")
	}
	dir := filepath.Join(home, ".hi-agent")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, "", err
	}

	keys = make([]string, 0, len(kv))
	for k := range kv {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by hi-agent setup-env. Do not edit exports by hand if you re-run setup.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "export %s=%s\n", k, shQuote(kv[k]))
		_ = os.Setenv(k, kv[k])
	}
	envSh := filepath.Join(dir, envShName)
	if err := os.WriteFile(envSh, []byte(b.String()), 0o600); err != nil {
		return keys, "", err
	}

	snippet := strings.Join([]string{
		markerBegin,
		fmt.Sprintf(`[ -f "$HOME/.hi-agent/%s" ] && . "$HOME/.hi-agent/%s"`, envShName, envShName),
		markerEnd,
		"",
	}, "\n")

	for _, name := range []string{".profile", ".bashrc", ".zshrc"} {
		path := filepath.Join(home, name)
		if err := ensureSourceBlock(path, snippet); err != nil {
			// 文件不存在则创建；其它错误继续尝试其余 rc
			if !os.IsNotExist(err) {
				// ensureSourceBlock 内部会创建；这里忽略个别失败
				continue
			}
		}
	}

	hint = fmt.Sprintf(
		"已写入 %s，并尝试挂到 ~/.profile、~/.bashrc、~/.zshrc。请执行 source ~/.hi-agent/%s 或重开终端。",
		envSh, envShName,
	)
	return keys, hint, nil
}

func shQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

func ensureSourceBlock(path, snippet string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return os.WriteFile(path, []byte(snippet), 0o644)
		}
		return err
	}
	text := string(data)
	if strings.Contains(text, markerBegin) {
		// 替换旧块
		start := strings.Index(text, markerBegin)
		end := strings.Index(text, markerEnd)
		if start >= 0 && end > start {
			end += len(markerEnd)
			text = text[:start] + strings.TrimSuffix(snippet, "\n") + text[end:]
			if !strings.HasSuffix(text, "\n") {
				text += "\n"
			}
			return os.WriteFile(path, []byte(text), 0o644)
		}
	}
	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	return os.WriteFile(path, []byte(text+snippet), 0o644)
}
